// <auto-generated />
using System;
using System.Collections.Generic;
using AiTalentGenome.VacancyService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiTalentGenome.VacancyService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VacancyDbContext))]
    [Migration("20260527141327_AddOutboxAndModelUpdates")]
    partial class AddOutboxAndModelUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiTalentGenome.VacancyService.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiAnalysisJson")
                        .HasColumnType("text");

                    b.Property<double?>("AiScore")
                        .HasColumnType("double precision");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CandidatePhone")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("CandidateSkills")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new List<string>());

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("CriticalMismatches")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new List<string>());

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("HhNegotiationId")
                        .HasColumnType("text");

                    b.Property<string>("HhResumeId")
                        .HasColumnType("text");

                    b.Property<string>("LastCompany")
                        .HasColumnType("text");

                    b.Property<string>("LastJobTitle")
                        .HasColumnType("text");

                    b.Property<string>("RawResumeText")
                        .HasColumnType("text");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TotalExperienceMonths")
                        .HasColumnType("integer");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HhNegotiationId")
                        .IsUnique()
                        .HasFilter("\"HhNegotiationId\" IS NOT NULL");

                    b.HasIndex("VacancyId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("AiTalentGenome.VacancyService.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccuredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("AiTalentGenome.VacancyService.Domain.Entities.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaName")
                        .HasColumnType("text");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<string>("HhId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("KeySkills")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new List<string>());

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("HhId")
                        .IsUnique()
                        .HasFilter("\"HhId\" IS NOT NULL");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("AiTalentGenome.VacancyService.Domain.Entities.Application", b =>
                {
                    b.HasOne("AiTalentGenome.VacancyService.Domain.Entities.Vacancy", "Vacancy")
                        .WithMany("Applications")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("AiTalentGenome.VacancyService.Domain.Entities.Vacancy", b =>
                {
                    b.OwnsOne("AiTalentGenome.VacancyService.Domain.ValueObjects.Salary", "Salary", b1 =>
                        {
                            b1.Property<Guid>("VacancyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("SalaryCurrency");

                            b1.Property<int?>("From")
                                .HasColumnType("integer")
                                .HasColumnName("SalaryFrom");

                            b1.Property<int?>("To")
                                .HasColumnType("integer")
                                .HasColumnName("SalaryTo");

                            b1.HasKey("VacancyId");

                            b1.ToTable("Vacancies");

                            b1.WithOwner()
                                .HasForeignKey("VacancyId");
                        });

                    b.Navigation("Salary");
                });

            modelBuilder.Entity("AiTalentGenome.VacancyService.Domain.Entities.Vacancy", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
