<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AiTalentGenome.Contracts" Version="1.0.23" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.80.0-pre1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AiTalentGenome.VacancyService.Application\AiTalentGenome.VacancyService.Application.csproj" />
      <ProjectReference Include="..\AiTalentGenome.VacancyService.Domain\AiTalentGenome.VacancyService.Domain.csproj" />
      <ProjectReference Include="..\AiTalentGenome.VacancyService.Infrastructure\AiTalentGenome.VacancyService.Infrastructure.csproj" />
    </ItemGroup>

</Project>
